In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification

In [6]:
X, y = make_classification(n_samples=100, n_features=2, n_informative=1, n_redundant=0, n_classes=2, n_clusters_per_class=1, random_state=41, hypercube=False, class_sep=10)

In [15]:
np.zeros(2)

array([0., 0.])

In [ ]:
class Perceptron:
    def __init__(self, learning_rate, epochs):
        self.weights = None
        self.bias = 1
        self.learning_rate = learning_rate
        self.epochs = epochs
        
    def activation(self, z):
        return 1 if z > 0 else 0

    def fit(self, X, y):
        self.weights = np.ones(X.shape[1])
        self.bias = 1
        for _ in range(self.epochs):
            for i in range(len(X)):
                z = np.dot(X[i], self.weights) + self.bias
                y_pred = self.activation(z)
                self.weights += self.learning_rate*(y[i] - y_pred)*X[i]
                self.bias += self.learning_rate*(y[i] - y_pred)
        return self.weights, self.bias
    
p = Perceptron(0.01, 10)
p.fit(X, y)

(array([1.2978027 , 0.23314214]), np.float64(0.9299999999999999))

In [37]:
p.weights, p.bias

(array([1.2978027 , 0.23314214]), np.float64(0.9299999999999999))